### ISSUE TITLE
Use vue-gwt to develop eclipse plugin

### ISSUE THREAD

**Issue by lapnd** [Axellience/vue-gwt#102]
Hi all,
Is it possible to write eclipse plugin using vue-gwt? for example, embed a browser to eclipse then the plugin (using vue-gwt) can be display on that browser.
Thank you!

**Comment by adrienbaron** [comment]
That’s something you might be able to achieve but I’d definitely not recommend it:
- you’ll get bad performance 
- It will be really hard if not impossible to connect your UI to the rest of the plug-in code
- Your UI won’t look native
- GWT is meant to target common browser not particularly web views

So in short; no this is not a valid use case IMO 👍
