### ISSUE TITLE
Demo Project is busted

### ISSUE THREAD

**Issue by mfreeman-xtivia** [Axellience/vue-gwt#113]
Have tried to compile the demo project (vue-gwt-demo) OOB with Maven 3.8.1 and 'mvn package' dies a miserable death.

Fails both on straight Windows and UbuntuWSL2

**Comment by adrienbaron** [comment]
Hi!

I just tried on my side and it seem to work. My configuration:

```
➜  vue-gwt-demo git:(master) java -version 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

```
➜  vue-gwt-demo git:(master) mvn -version   
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

Steps I followed:
- Cloned `master` from https://github.com/VueGWT/vue-gwt-demo
- Ran `mvn clean package`
- Ran `mvn gwt:devmode`
- On the GWT Dev window clicked `Launch Default Browser`
![image](https://user-images.githubusercontent.com/4410247/124824369-3265ec80-df6a-11eb-8dd7-7604808f2746.png)

![image](https://user-images.githubusercontent.com/4410247/124824421-427dcc00-df6a-11eb-8324-d2f8aa4dd9ed.png)

Do you have details of the error you are encountering?

**Comment by mfreeman-xtivia** [comment]
Did the git clone, then mvn clean install. Receive this error:
```
...
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (640 kB at 992 kB/s)
[INFO] Compiling 7 source files to /home/dev/temp/vue-gwt-demo/target/vue-gwt-demo-1.0-beta-9/WEB-INF/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  58.422 s
[INFO] Finished at: 2021-07-07T15:32:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project vue-gwt-demo: Fatal error compiling: java.lang.NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by adrienbaron** [comment]
Thank you for the fast reply! Hum this is weird, which version of Java are you using? This might help me reproduce 👍

**Comment by mfreeman-xtivia** [comment]
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /home/dev/.sdkman/candidates/java/11.0.11.hs-adpt
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by adrienbaron** [comment]
Indeed I just tried and I do get an NPE at build time with OpenJDK 11. Not sure if the problem is 11 or OpenJDK VS Oracle.
If you want to have a try, Oracle Java 8 should work, in the meantime I'll try to see what's missing on it for it to run on OpenJDK 11, I'm pretty sure it used to work there 🤔 .

**Comment by adrienbaron** [comment]
Ok, good news the tests are working on OpenJDK 11. They build an actual app and test inside a headless broaser so I'm confident it does work:
```
[INFO] HeadlessChrome 91.0.4472 (Mac OS X 10.15.7): Executed 229 of 229 SUCCESS (1.725 secs / 0.096 secs)
[INFO] TOTAL: 229 SUCCESS
```

However I haven't figured out why the demo project isn't working yet, still looking into it.

**Comment by adrienbaron** [comment]
@mfreeman-xtivia Ok figured it out, demo project was using an old version of Vue GWT that didn't support Java 11 🤦 . The new version doesn't rely on Nashorn anymore (that got booted from Java) and uses [Rhino](https://github.com/mozilla/rhino) instead 👍 

I just pushed a commit to `master`, it should work now 👍 ! Thanks again for the report!

**Comment by mfreeman-xtivia** [comment]
Works perfectly now!!! Thank you
