### ISSUE TITLE
How to run template generator during "GWT Compile" ?

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt#13]
Currently, if I have broken html template, "GWT Compile" passed just fine, without any errors. Then I run superdev mode on jetty and getting error only when code server starts compiling of my project. That's ok, but would be nice to get errors during "GWT Compile" stage.

**Comment by adrienbaron** [comment]
Hi!

Short answer: Not yet.
Long answer: For now we use a GWT2 generator to start the compilation of your template, and those are run when the code server compiles.
In the future, we intend to move to Annotation Processing for that part too (actually there is a working annotation processor on the feature/gwt3 branch, but it's very much a test). The only reason we are not pushing this one yet is that Annotation Processors can't be triggered by resources changes. Which mean that it won't run automatically if you touch the HTML file.
Either an IDE plugin or some watcher config would be necessary to make it run each time you touch the HTML. I got some success creating a File Watcher in IntelliJ that "touch" the corresponding Java file each time you edit the HTML, but I'm not sure that's a solution for everyone.

**Comment by slavap** [comment]
@adrienbaron In Eclipse there are project builders, they have file watchers integrated, I’m using them for generating java files based on ui.xml files, so I don’t need to write @UiField annotations manually. I can provide code if you need more details.

**Comment by adrienbaron** [comment]
@slavap That would be great! We will probably need it anyway for GWT3. I will probably ask the opinion of the community on Gitter to know what they think about moving from Generators to Annotation Processor + IDE config as both have advantages and issues.

**Comment by slavap** [comment]
@adrienbaron Actually, it's quite simple in Eclipse, I bet Idea should have something similar.
```java
public class UiBinderToJavaGenerator {
    public static void main(final String[] args) throws Exception {
        // here goes the auto-generation logic, you can read and write files
    }
}
```
![image](https://user-images.githubusercontent.com/4129763/33151260-2fe8ee36-cf8c-11e7-96bf-9ca43851ca99.png)

![image](https://user-images.githubusercontent.com/4129763/33151298-5c1ccd2e-cf8c-11e7-8501-d5d01f5d9e8c.png)

![image](https://user-images.githubusercontent.com/4129763/33151307-68337b8a-cf8c-11e7-8204-c4003dad9ba0.png)

"Specify Resources..." button configures folders watcher (usually it's all folders in my project src/client)
Works very fast, especially if you check (in generator code) files hashes before generation, i.e. don't re-generate not changed files every time.

**Comment by slavap** [comment]
@adrienbaron ui.xml to java generating code, based on Tessell http://www.tessell.org/
Perhaps it could be useful for you somehow :-)
[UiBinderToJava.zip](https://github.com/Axellience/vue-gwt/files/1497637/UiBinderToJava.zip)

**Comment by adrienbaron** [comment]
Closing this issue for now, thanks for the info :). Will have to look into all of this ;)
