### ISSUE TITLE
Add @Emit("myEvent") annotation for methods

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt#14]
The same way as implemented in https://github.com/kaorun343/vue-property-decorator

**Comment by adrienbaron** [comment]
Thank you for the feedback, we will consider adding this, seems like a good idea.

**Comment by slavap** [comment]
@adrienbaron Thank you, it works. Though there is a small problem, for some reason emit method must be declared as public:
```java
    @Emit("input") @JsMethod public/*mandatory!???*/ void onChanged(String value) {
        DomGlobal.console.log(value);
    }

    @Computed public void setVal(String val) {
        onChanged(val);
    }

    @Computed public String getVal() {
        return value;
    }

```

**Comment by adrienbaron** [comment]
@slavap To $emit, we generate a method in the generated `ComponentJsType`. This `ComponentJsType` inherit from your VueComponent and call the super method, then call `$emit`. This makes that the method cannot be private (must be at least `protected`).
I've checked and there appears to be a bug if the method is `package-protected`, so for now it's better to just declare the method as `public` or `protected`.
Maybe implementing the wrapping differently would avoid the `package-protected` bug.

**Comment by slavap** [comment]
@adrienbaron  Yes, package protected is not working in my case, I’ve declared it public as workaround. Also would be nice if emit raises warning if method not marked with JsMethod annotation.

**Comment by adrienbaron** [comment]
@slavap I think it already does emit an error if you don't have the `@JsMethod` annotation 👍 

For example:
`Error:java: The method "myEventWithValue2" annotated with @Emit must also be annotated with @JsMethod in Component: com.axellience.vuegwtexamples.client.examples.emitannotation.EmitAnnotationComponent`

**Comment by slavap** [comment]
@adrienbaron have to check once again, may be I missed the warning, but I was under impression I didn’t get it when JsMethod was missing.

**Comment by adrienbaron** [comment]
@slavap It's fired by the annotation processor, so it might be easier to miss
