### ISSUE TITLE
v-bind="$props" in component template

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt#17]
Because in VueComponent $props is declared as private, and $props() is not @JsMethod, template compilation fails.

See (just for reference): https://github.com/vuejs/vue/issues/5606

**Comment by adrienbaron** [comment]
Indeed, the template compiler checks that Objects/Methods are available in context, and this is not the case for $props.

For now you can declare a method in your component to expose the $props if you wish:
```java
@JsMethod
public Object get$props() {
    return super.$props();
}
```

Then you should be able to pass it in your template:
```html
<my-child :props="get$props()"/>
```

We will expose $props() in the template in the next beta release. We will also try to improve typings (for now $props() returns `Object`).
Maybe we will change it to a `JsPropertyMap<Object>`, so you can do: `$props().get("myProp")` in your template.
We are also thinking of adding `public Object $props(String propertyName)`. This way you will be able to do `$props("myProp")` if you wish.
What do you think about it?

**Comment by slavap** [comment]
@adrienbaron Both options sounds good to me.

**Comment by adrienbaron** [comment]
@slavap Ok great! We will add this then.
