### ISSUE TITLE
Documentation for @PropValidator

### ISSUE THREAD

**Issue by slavap** [Axellience/vue-gwt#20]
It would be nice to mention in documentation that validator method should return boolean, i.e.
```java
@PropValidator(propertyName = "size")
boolean sizeValidator(String value) {
    return "large".equals(value) || "small".equals(value);
}
```
Also declare propertyName as default, so it would be possible to use 
```java 
@PropValidator("size") 
```

**Comment by adrienbaron** [comment]
Indeed, and the annotation processor should probably fail if it does't return a boolean. I add this as improvements.
If you have time and want to try we also welcome external contributions ;).

**Comment by slavap** [comment]
@adrienbaron Not sure I can contribute currently with the code, but I have such plans for 2018.

**Comment by adrienbaron** [comment]
Ok I'll see to do this then 😉

**Comment by adrienbaron** [comment]
I've just fixed 2 of the problem of this issue.

However regarding the default property to be able to use:
```java
@PropValidator("size") 
```

This would force to rename `propertyName` to `value`. This would be a breaking change, and for consistency we would have to do that on the other annotation that take `propertyName` as parameter (like `@Watch`).
I'm not sure the breaking change is worth it... But I would be glad to get your input on this.

**Comment by slavap** [comment]
@adrienbaron breaking change is not good of course, but in this case it makes sense IMO to do that. Existing code could be easily fixed, new code will be cleaner and shorter. Anyway, it’s up to you.

**Comment by adrienbaron** [comment]
Hum, I guess you are right. And better to do breaking changes early to improve the API.
So I'll follow your recommendation and do that 👍

**Comment by slavap** [comment]
@adrienbaron tested in beta6-snapshot, works, getting error on compile:
[ERROR] Method variantValidator annotated with PropValidator must return a boolean. In VueComponent: com.axellience.vuegwtdemo.client.components.bootstrap.JqmButton
