### ISSUE TITLE
what ajax library suggest to use?

### ISSUE THREAD

**Issue by nile** [Axellience/vue-gwt#29]
hi all , with gwt what library suggest to use?

**Comment by adrienbaron** [comment]
In our team we are using RestyGWT for that: https://resty-gwt.github.io/.

I'm closing the issue. For support it's better to ask questions on our Gitter: https://gitter.im/Axellience/vue-gwt. Don't hesitate to ask there if you have more questions.

**Comment by nile** [comment]
thanks a lot
