### ISSUE TITLE
Move from vue-custom-element to the official Vue WC wrapper

### ISSUE THREAD

**Issue by adrienbaron** [Axellience/vue-gwt#35]
[Web Component support](https://axellience.github.io/vue-gwt/advanced/custom-elements.html) in Vue GWT is based on [vue-custom-element](https://github.com/karol-f/vue-custom-element).
There is now an official Wrapper from the Vue team: [vue-web-component-wrapper](https://github.com/vuejs/vue-web-component-wrapper).

We should update Vue GWT to use this one as it will be supported in the future.

**Comment by slavap** [comment]
@adrienbaron It slightly bothers me: "IE11 and below not supported". May be both implementations (vue-custom-element and vue-web-component-wrapper) should be available with ability to configure which one to use.

**Comment by adrienbaron** [comment]
@slavap Oh I didn't understand that at first. I thought they just meant IE11 required polyfill (like for vue-custom-element). You are right better old off for now, we can reconsider when dropping IE11 support in the future 👍
